version: '3.8'

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - excel_data_volume:/app/excel_data
      - ./logs:/app/logs
    depends_on:
      - db

  telegram_bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - excel_data_volume:/app/excel_data
      - ./logs:/app/logs
    depends_on:
      - db

volumes:
  postgres_data:
  excel_data_volume:
