"""create orders table

Revision ID: 954771e6af4f
Revises: 
Create Date: 2024-04-22 01:42:40.841657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '954771e6af4f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('lastChangeDate', sa.DateTime(), nullable=False),
    sa.Column('warehouseName', sa.String(), nullable=False),
    sa.Column('countryName', sa.String(), nullable=False),
    sa.Column('oblastOkrugName', sa.String(), nullable=False),
    sa.Column('regionName', sa.String(), nullable=False),
    sa.Column('supplierArticle', sa.String(), nullable=False),
    sa.Column('nmId', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('techSize', sa.String(), nullable=False),
    sa.Column('incomeID', sa.Integer(), nullable=False),
    sa.Column('isSupply', sa.Boolean(), nullable=False),
    sa.Column('isRealization', sa.Boolean(), nullable=False),
    sa.Column('totalPrice', sa.Float(), nullable=False),
    sa.Column('discountPercent', sa.Integer(), nullable=False),
    sa.Column('spp', sa.Float(), nullable=False),
    sa.Column('finishedPrice', sa.Float(), nullable=False),
    sa.Column('priceWithDisc', sa.Float(), nullable=False),
    sa.Column('isCancel', sa.Boolean(), nullable=False),
    sa.Column('cancelDate', sa.DateTime(), nullable=False),
    sa.Column('orderType', sa.String(), nullable=False),
    sa.Column('sticker', sa.String(), nullable=False),
    sa.Column('gNumber', sa.String(), nullable=False),
    sa.Column('srid', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('srid', name=op.f('uq_orders_srid'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
