"""add date column sales

Revision ID: ddd6688bbe84
Revises: db4eb538e2ed
Create Date: 2024-04-22 14:21:46.340323

"""
from __future__ import annotations

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "ddd6688bbe84"
down_revision: Union[str, None] = "db4eb538e2ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sales", sa.Column("date", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sales", "date")
    # ### end Alembic commands ###
